// Generated by CoffeeScript 1.6.2
var BattleStage,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BattleStage = (function(_super) {
  __extends(BattleStage, _super);

  function BattleStage() {
    BattleStage.__super__.constructor.apply(this, arguments);
    true;
  }

  BattleStage.prototype.end = function() {
    message.hide.call(message);
    return player.products['tomato'].amount = 0;
  };

  return BattleStage;

})(Stage);
