// Generated by CoffeeScript 1.6.2
$(function() {
  console.log('Gryo begin tracking');
  window.acc = {
    x: 0,
    y: 0,
    z: 0
  };
  return window.ondevicemotion = function(e) {
    var change, i, string, x, y, z, _i, _ref;

    x = e.accelerationIncludingGravity.x;
    y = e.accelerationIncludingGravity.y;
    z = e.accelerationIncludingGravity.z;
    change = Math.abs(acc.x - x) + Math.abs(acc.y - y) + Math.abs(acc.z - z);
    string = '';
    for (i = _i = 1, _ref = Math.round(change); 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      string += 'XXX';
    }
    console.log(string);
    $(".money").html(change);
    window.acc = {
      x: x,
      y: y,
      z: z
    };
    if (change > 30) {
      return alert("You win!");
    }
  };
});
