// Generated by CoffeeScript 1.6.2
$(function() {
  var moving_average_samples;

  console.log('Gryo begin tracking');
  window.acc = {
    x: 0,
    y: 0,
    z: 0
  };
  window.avg_acc = false;
  moving_average_samples = 50;
  window.censor_gyroscope = false;
  return window.ondevicemotion = function(e) {
    var change, i, string, x, y, z, _i, _ref;

    x = e.accelerationIncludingGravity.x;
    y = e.accelerationIncludingGravity.y;
    z = e.accelerationIncludingGravity.z;
    change = Math.abs(acc.x - x) + Math.abs(acc.y - y) + Math.abs(acc.z - z);
    string = '';
    for (i = _i = 1, _ref = Math.round(change); 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      string += 'XXX';
    }
    console.log(string);
    window.acc = {
      x: x,
      y: y,
      z: z
    };
    if (change > 20 && !window.censor_gyroscope) {
      window.censor_gyroscope = true;
      window.stage.bump.call(window.stage);
      return setTimeout(function() {
        return window.censor_gyroscope = false;
      }, 500);
    }
  };
});
