// Generated by CoffeeScript 1.6.2
window.handleResize = function() {
  $('.statusbar').css('font-size', (0.9 * $('.statusbar').height()) + 'px');
  return $(window).scrollTop(0);
};

$(window).bind('resize', window.handleResize);

$(function() {
  window.handleResize();
  if (($.ui == null) || ($.mobile == null)) {
    return location.reload(true);
  }
});

window.updateStatusBar = function() {
  return $('.money').html('$' + player.gold);
};

window.updateCountdown = function() {
  return $('.countdown').html(stage.time);
};
