// Generated by CoffeeScript 1.6.2
$(window).bind('resize', function() {
  $('.statusbar').css('font-size', (0.9 * $('.statusbar').height()) + 'px');
  return $(window).scrollTop(0);
});

window.updateStatusBar = function() {
  return $('.money').html('$' + player.gold);
};
