// Generated by CoffeeScript 1.6.2
var handleResize;

handleResize = function() {
  return $('.statusbar').css('font-size', (0.9 * $('.statusbar').height()) + 'px');
};

$(window).bind('resize', handleResize);

window.updateStatusBar = function() {
  return $('.money').html('$' + player.gold);
};
