// Generated by CoffeeScript 1.6.2
window.config = [];

window.config.websocket_url = "ws://192.168.0.106:8888/json";

window.config.server_version = 0;

$(function() {
  window.socket = new WebSocket(window.config.websocket_url);
  window.jevent('SocketOpened', function() {});
  console.log('The socket was opened.');
  socket.onopen = function() {
    console.log("Socket connection opened successfully.");
    window.pycon = new PyAPI(window.socket);
    return window.go();
  };
  return socket.onclose = function() {
    console.log("Socket connection was closed, unexpectedly.");
    return alert("I don't know why, but the socket was closed (!)");
  };
});

window.go = function() {
  window.stage = window.productionstage = new ProductionStage();
  pycon.register_for_event('playerCountChanged', function(data) {
    console.log('Player count changed: ', data);
    return $('.playercount').html(data.count);
  });
  return pycon.register_for_event('stageBegin', function(data) {
    window.stage.end();
    if (data.stageType === 'Production') {
      return window.stage = new ProductionStage();
    } else if (data.stageType === 'Trading') {
      return window.stage = new TradingStage();
    } else {
      throw 'illegal :(';
    }
  });
};
