// Generated by CoffeeScript 1.6.2
window.Message = (function() {
  function Message() {
    this.dom_selector = '.message';
    this.timeout = 5;
  }

  Message.prototype.display = function(title, text, clickable, duration) {
    var me;

    if (clickable == null) {
      clickable = true;
    }
    if (duration == null) {
      duration = null;
    }
    me = this;
    $('.overlay').show();
    $(this.dom_selector).children('.title').html(title);
    $(this.dom_selector).children('.text').html(text);
    $(this.dom_selector).show();
    if (clickable) {
      $(this.dom_selector).tap(function() {
        return me.hide.call(me);
      });
    }
    if (duration != null) {
      return setTimeout(function() {
        return window.message.hide.call(message);
      }, duration * 1000);
    }
  };

  Message.prototype.hide = function() {
    $(this.dom_selector).unbind();
    $(this.dom_selector).hide();
    return $('.overlay').hide();
  };

  return Message;

})();

window.message = new Message();
