// Generated by CoffeeScript 1.6.2
window.Player = (function() {
  function Player() {
    var p, _i, _len, _ref;

    this.gold = 0;
    this.products = [];
    this.productionfacilities = [];
    _ref = ['tomato', 'blueberry', 'purple', 'corn'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      p = _ref[_i];
      this.products[p] = new Product(p);
      this.productionfacilities[p] = new ProductionFacility(this.products[p]);
    }
    this.products['tomato'].color = 'red';
    this.products['blueberry'].color = 'blue';
    this.products['purple'].color = 'purple';
    this.products['corn'].color = 'orange';
    true;
  }

  Player.prototype.giveGold = function(amount) {
    this.gold += amount;
    return updateStatusBar();
  };

  Player.prototype.doYes = function() {
    return true;
  };

  return Player;

})();

window.Product = (function() {
  function Product(name) {
    this.name = name;
    this.amount = 5;
    this.price = 0;
    this.color = "green";
    true;
  }

  Product.prototype.getPrice = function() {
    return this.price = Math.round(Math.random() * 100, 2);
  };

  Product.prototype.generator = function() {
    return player.productionfacilities[this.name];
  };

  return Product;

})();

window.ProductionFacility = (function() {
  function ProductionFacility(product) {
    this.capacity = 0;
    true;
  }

  ProductionFacility.prototype.generateProduct = function() {
    if (this.capacity * Math.random() > 1) {
      return true;
    } else {
      return false;
    }
  };

  return ProductionFacility;

})();

window.player = new Player();

player.giveGold(5);
