// Generated by CoffeeScript 1.6.2
window.Player = (function() {
  function Player() {
    var p, _i, _len, _ref;

    this.gold = 10;
    this.products = [];
    this.productionfacilities = [];
    _ref = ['tomato', 'blueberry', 'purple', 'corn'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      p = _ref[_i];
      this.products[p] = new Product(p);
      this.productionfacilities[p] = new ProductionFacility(this.products[p]);
    }
    true;
  }

  Player.prototype.doYes = function() {
    return true;
  };

  return Player;

})();

window.Product = (function() {
  function Product(name) {
    this.name = name;
    true;
  }

  return Product;

})();

window.ProductionFacility = (function() {
  function ProductionFacility(product) {
    this.capacity = 0;
    true;
  }

  ProductionFacility.prototype.generateProduct = function() {
    if (this.capacity * Math.random() > 1) {
      return true;
    } else {
      return false;
    }
  };

  return ProductionFacility;

})();

window.player = new Player();

player.gold = 5;
