// Generated by CoffeeScript 1.6.2
window.ProductionStage = (function() {
  function ProductionStage() {
    var me;

    me = this;
    this.productions = [];
    $('.box').each(function() {
      return me.productions.push(new Production($(this), me));
    });
    $('.ready').tap(function() {
      return pycon.transaction({
        'action': 'ready'
      }, true);
    });
    true;
  }

  return ProductionStage;

})();

window.Production = (function() {
  function Production(dom_object, productionstage) {
    var me;

    this.dom_object = dom_object;
    this.productionstage = productionstage;
    me = this;
    this.capacity = 0;
    this.dom_object.tap(function() {
      return me.invest.call(me, 1);
    });
    true;
  }

  Production.prototype.invest = function(amount) {
    this.capacity += amount;
    this.needsRefresh();
    return true;
  };

  Production.prototype.needsRefresh = function() {
    this.dom_object.children('span').html(this.capacity);
    return true;
  };

  return Production;

})();
