// Generated by CoffeeScript 1.6.2
window.Stage = (function() {
  function Stage() {
    window.updateStatusBar();
    true;
  }

  Stage.prototype.bump = function() {
    return true;
  };

  Stage.prototype.trade_complete = function() {
    return true;
  };

  Stage.prototype.price_updated = function() {
    return true;
  };

  Stage.prototype.timer_begin = function() {
    return true;
  };

  return Stage;

})();
