// Generated by CoffeeScript 1.6.2
window.Stage = (function() {
  function Stage() {
    true;
  }

  Stage.prototype.bump = function() {
    return true;
  };

  Stage.prototype.trade_complete = function() {
    return true;
  };

  return Stage;

})();
